### ISSUE TITLE
Profile Setup Error

### ISSUE THREAD

**Issue by aishahisham1** [Roomah/Roomah-Prototype#22]
Current issue:
If a user does not go through with the profile set up page, an error occurs where no results will display in 'find housemates' page. This error applies to other users when they're browsing the 'find housemates' page. 

possible solutions:
fix 'null' value

**Comment by ShafiqAiman** [comment]
Aishah and I solved these issues by setting the table userprofile to have default values and then filter out those profiles from the list of results.
