### ISSUE TITLE
User Payment Process

### ISSUE THREAD

**Issue by aishahisham1** [Roomah/Roomah-Prototype#24]
Instead of the user making payments after creating a listing, it would be better if they made payment before creating a listing. This would be better for the user experience. But this can be implemented later in the development.

**Comment by ShafiqAiman** [comment]
@aishahisham1 After having the discussion, we have agreed to put pricing plans/packages (picture)  first before the user fills up the form and then the payment can be made.  Therefore, this issue will be closed. 

![image](https://user-images.githubusercontent.com/32039212/148790723-d045c73e-c265-4909-b52a-004b1e085d98.png)

**Comment by ShafiqAiman** [comment]
@aishahisham1  After having the discussion, we have agreed to put pricing plans/packages (picture)  first before the user fills up the form and then the payment can be made.  Therefore, this issue will be closed. 

![image](https://user-images.githubusercontent.com/32039212/148790723-d045c73e-c265-4909-b52a-004b1e085d98.png)
